### ISSUE TITLE
issue while fetching historic data

### ISSUE THREAD

**Issue by tarunmcom** [TradeViaPython/Kite_Zerodha#10]
all the fuctions working for me except fetching historic data. The error:-

- Traceback (most recent call last):
-   File "C:\Users\admin\Downloads\kite\main.py", line 11, in <module>
-     print(kite.historical_data(instrument_token, from_datetime, to_datetime, interval, continuous=False, oi=False))
-   File "C:\Users\admin\Downloads\kite\kite_trade.py", line 102, in historical_data
-     lst = self.session.get(
- TypeError: 'NoneType' object is not subscriptable

**Comment by 2sahil3** [comment]
That's probably because you have given one or more arguments wrongly.
For example in my case, the wrong parameter was the instrument token.
so i changed it to some other token (it was of tata steel), you can have token values by printing the instruments 
this line: # print(kite.instruments())
Also whenever you face this error try to understand the arguments since if we give wrong arguments, the GET request will return a NoneType Object(correct me if i am wrong) and that means that u didnt got your desired output.
Thankyou.

**Comment by tarunw07** [comment]
I also think you're probably using the wrong token. My guess would be that you are using an exchange token instead. The instrument token here is different from the exchange token(which is used generally by other API providers).

To fetch the instrument_token for the corresponding exchange_token, you can fetch all the instruments using kite.instruments("NFO") API and its response have both instrument_token and exchange_token.

**Comment by jenish99** [comment]
Give values of "instrument_token, from_datetime, to_datetime, interval, continuous=False, oi=False" used in program here.
