### ISSUE TITLE
How to sell the after i buy,  NFO : option chain

### ISSUE THREAD

**Issue by AggressiveAbhi** [TradeViaPython/Kite_Zerodha#11]
I purchased BANK NIFTY 42000 CE then if i want to set target or stoploss , how can i do , because if i execute sell order it is showing option selling

**Comment by jenish99** [comment]
Place sell order only after execute buy order.

**Comment by Soumeniisc** [comment]
kite.place_order(variety=kite.VARIETY_REGULAR,
                         exchange=kite.EXCHANGE_NFO,
                         tradingsymbol="BANKNIFTY2360143700CE",
                         transaction_type=kite.TRANSACTION_TYPE_BUY,
                         quantity=1,#
                         product=kite.PRODUCT_NRML,
                         order_type=kite.ORDER_TYPE_SL, #this limiting order will trigger when price reaches 90.9 and limit price is 91.0
                         price=44900,
                         disclosed_quantity=None,
                         trigger_price=44800,
                         squareoff=None,
                         stoploss=None,
                         trailing_stoploss=None,
                         tag="TradeViaPython")

For this i am getting following error:
order_id = self.session.post(f"{self.root_url}/orders/{variety}",
TypeError: 'NoneType' object is not subscriptable

**Comment by nitin4646** [comment]
any solution on above query, I am also getting same error

**Comment by jenish99** [comment]
Don't place SL order without stop loss limit.

Or try to place limit order

**Comment by Shivayogihc** [comment]
even i am getting this error, order function

# Place Order
order = kite.place_order(variety=kite.VARIETY_REGULAR,
                         exchange=kite.EXCHANGE_NFO,
                         tradingsymbol="BANKNIFTY2371345200CE",
                         transaction_type=kite.TRANSACTION_TYPE_BUY,
                         quantity=1,
                         product=kite.PRODUCT_NRML,
                         order_type=kite.ORDER_TYPE_MARKET,
                         price=None,
                         validity=None,
                         disclosed_quantity=None,
                         trigger_price=None,
                         squareoff=None,
                         stoploss=None,
                         trailing_stoploss=None,
                         tag="TradeViaPython")

print(order)

**Errror
Traceback (most recent call last):
  File "/Users/shivyogi/Desktop/Automate_Trading/telegram-analysis/main.py", line 9, in <module>
    order = kite.place_order(variety=kite.VARIETY_REGULAR,
  File "/Users/shivyogi/Desktop/Automate_Trading/telegram-analysis/kite_trade.py", line 134, in place_order
    order_id = self.session.post(f"{self.root_url}/orders/{variety}",
TypeError: 'NoneType' object is not subscriptable


How to fix it, Please anyone Help

**Comment by Shivayogihc** [comment]
The thing is when tradingsymbol='ACC', it works fine. If the tradingsymbol='BANKNIFTY2371345200CE' that is options then it shows the above error

**Comment by jenish99** [comment]
Try ITM contract.

**Comment by jenish99** [comment]
Try 45000 ce/pe if Banknifty trading around 45000

**Comment by Shivayogihc** [comment]
<img width="1728" alt="Screenshot 2023-07-12 at 11 25 35 AM" src="https://github.com/TradeViaPython/Kite_Zerodha/assets/88485343/06060d7d-793f-448b-a91e-1177a8ff802a">
The above i did, as you said.
After removing [order_id] from place_order function.
<img width="1728" alt="Screenshot 2023-07-12 at 11 27 35 AM" src="https://github.com/TradeViaPython/Kite_Zerodha/assets/88485343/1fe2be41-76f0-47c5-ace0-61363ae45b03">
Result:
<img width="1728" alt="Screenshot 2023-07-12 at 11 28 05 AM" src="https://github.com/TradeViaPython/Kite_Zerodha/assets/88485343/0fa8330f-7792-4efb-bcb8-d0b5cf56d2bd">


> Try 45000 ce/pe if Banknifty trading around 45000

**Comment by Shivayogihc** [comment]
> Try 45000 ce/pe if Banknifty trading around 45000

Not working, any other Solution ?

**Comment by coprem** [comment]
@Shivayogihc I am able use the code without any issue, try putting everything into one line of code may be indentation is the issue.

`order = kite.place_order(variety=kite.VARIETY_REGULAR,exchange=kite.EXCHANGE_NFO,tradingsymbol="BANKNIFTY2371345200CE",transaction_type=kite.TRANSACTION_TYPE_BUY,quantity=1,product=kite.PRODUCT_NRML,order_type=kite.ORDER_TYPE_MARKET,price=None,validity=None,disclosed_quantity=None,trigger_price=None,squareoff=None,stoploss=None,trailing_stoploss=None,tag="TradeViaPython")`

**Comment by manojSingh199** [comment]
@TradeViaPython or Anyone 
Please reply I'm also facing same issue.
