### ISSUE TITLE
GotThis Error Today

### ISSUE THREAD

**Issue by nayan1601** [TradeViaPython/Kite_Zerodha#17]
Traceback (most recent call last):
  File "/home/ubuntu/Kite_Zerodha/main.py", line 21, in <module>
    data = kite.quote(["NSE:BANKBARODA"])
  File "/home/ubuntu/Kite_Zerodha/kite_trade.py", line 89, in quote
    data = self.session.get(f"{self.root_url}/quote", params={"i": instruments}, headers=self.headers).json()["data"]
KeyError: 'data'

**Comment by Gaurav7888** [comment]
same i am also getting this error

**Comment by niravchotai27** [comment]
same error is there any solution for this?

**Comment by natarajsbhargav** [comment]
Those API's are only available for users who have subscribed for the Kite APIs
